#![allow(unused)]

mod binary_tree_inorder_traversal;
mod binary_tree_preorder_traversal;
mod binary_tree_postorder_traversal;
mod invert_binary_tree;
mod maximum_depth_of_binary_tree;
mod diameter_of_binary_tree;
mod balanced_binary_tree;
mod same_tree;
mod subtree_of_another_tree;
mod merge_two_binary_tree;
mod path_sum;
mod range_sum_of_bst;
mod leaf_similar_trees;
mod evaluate_boolean_binary_tree;
mod closest_binary_search_tree_value;
mod minimum_absolute_difference_in_bst;
mod minimum_distance_between_bst_nodes;
mod symmetric_tree;
mod binary_tree_vertical_order_traversal;
mod binary_tree_longest_consecutive_sequence;
mod create_binary_tree_from_descriptions;
mod construct_string_from_binary_tree;
mod lowest_common_ancestor_of_a_binary_tree;
mod lowest_common_ancestor_of_a_binary_search_tree;
mod insert_into_a_binary_search_tree;
mod delete_node_in_a_bst;
mod binary_tree_level_order_traversal;
mod binary_tree_right_side_view;
mod reverse_odd_levels_of_binary_tree;
mod kth_largest_sum_in_a_binary_tree;
mod cousins_in_binary_tree;
mod maximum_level_sum_of_a_binary_tree;
mod kth_largest_perfect_subtree_size_in_binary_tree;
mod cousins_in_binary_tree_2;
mod linked_list_in_binary_tree;
mod binary_tree_zigzag_level_order_traversal;
mod find_duplicate_subtrees;
mod check_completeness_of_a_binary_tree;
mod maximum_width_of_binary_tree;
mod count_good_nodes_in_binary_tree;
mod validate_binary_search_tree;
mod kth_smallest_element_in_a_bst;
mod sum_root_to_leaf_numbers;
mod find_bottom_left_tree_value;
mod find_largest_value_in_each_tree_row;
mod pseudo_palindromic_paths_in_a_binary_tree;
mod even_odd_tree;
mod smallest_string_starting_from_leaf;
mod delete_leaves_with_a_given_value;

fn main() {
    delete_leaves_with_a_given_value::main();
}
